### ISSUE TITLE
Fish abbreviations

### ISSUE THREAD

**Issue by fred** [ahmetb/kubectl-aliases#13]
Would be good to have better fish integration.
However this script can do it:

```ruby
#!/usr/bin/env ruby

lines = File.read('.kubectl_aliases').split("\n")

script = "#!/usr/local/bin/fish\n\n"

lines.each do |line|
  abbr = line.match(/alias (\w+)/)[1]
  cmd = line.match(/\='(.+)'/)[1]
  script << "abbr -a #{abbr} #{cmd};\n"
end

File.write('/tmp/fish-k8s-abbrs', script)

`chmod +x /tmp/fish-k8s-abbrs`
`fish -c /tmp/fish-k8s-abbrs`
`rm /tmp/fish-k8s-abbrs`
```

**Comment by ahmetb** [comment]
Sounds like you can just download ~/.kubectl_aliases and do:


   source <(cat ~/.kubectl_aliases | sed 's/alias /abrr -a /' | sed "s/='/ '/")

in bash?

**Comment by scnewma** [comment]
For the fish folks that find this. You can put this function in your `~/.config/fish/functions/` folder and it will automatically pull down the latest abbreviations from this repo and convert them as shown above.

```
function __update_kubectl_abbrs
    curl -s -o /tmp/fish-k8s-abbrs https://raw.githubusercontent.com/ahmetb/kubectl-aliases/master/.kubectl_aliases
    cat /tmp/fish-k8s-abbrs | sed 's/alias /abbr -a /' | sed "s/='/ '/" > ~/.config/fish/conf.d/kubectl_abbrs.fish
    rm /tmp/fish-k8s-abbrs
end
```

Thanks for the abbreviations!
