### ISSUE TITLE
No aliases for `kubectl logs -p <podName>`

### ISSUE THREAD

**Issue by henricook** [ahmetb/kubectl-aliases#17]
I often use this command to get logs of the previous container in a pod (e.g. in the event of pod crash) - but it's not in the aliases list, could something be added?

**Comment by ahmetb** [comment]
klo is there. Not sure if -p flag exists?

**Comment by henricook** [comment]
![image](https://user-images.githubusercontent.com/82004/51800483-287f2180-2227-11e9-82f8-043c0c64acaa.png)

**Comment by henricook** [comment]
I find myself using it a lot and was thinking maybe something like klop would be fun

**Comment by ahmetb** [comment]
oh wow I wasn't aware of `-p`. Do you mind adding it to the script like:

        ('lo', 'logs -f', None, None),
        ('lop', 'logs -f -p', None, None),

**Comment by henricook** [comment]
Happy to! 👍

**Comment by henricook** [comment]
https://github.com/ahmetb/kubectl-aliases/pull/19

How am I looking?
