### ISSUE TITLE
Completion not working with Bash

### ISSUE THREAD

**Issue by weibeld** [ahmetb/kubectl-aliases#21]
With zsh, programmable completion works with the aliases as it would with the full commands. 

For example:

~~~bash
# Displays all sub-commands of kubectl
k [tab]
# Displays all resource objects
kg [tab]
# Displays all pods
kgpo [tab]
~~~

However, this doesn't work with Bash. If you do the same in Bash, there is no programmable completion invoked at all for the aliases.

I use Bash 5.0 on macOS with [bash-completion 2.8](https://github.com/scop/bash-completion) installed.

Do you have any ideas on this? Is this the normal behaviour of Bash, or can it be fixed somehow?

**Comment by ahmetb** [comment]
Sounds like a bash question and not about kubectl-aliases. :) I personally use zsh, too so I don't hit this. I recommend you ask this on https://superuser.com.

**Comment by weibeld** [comment]
It is a Bash issue. I just asked because you mention in your [post](https://ahmet.im/blog/kubectl-aliases/) that `kubectl` completion keeps working with the aliases. So, in that case, this only holds for Zsh, but not for Bash.

**Comment by imduffy15** [comment]
@weibeld did you have a resolution for this?

**Comment by weibeld** [comment]
@imduffy15 yes, you can use [complete-alias](https://github.com/cykerway/complete-alias). The following enables completion for each of the kubectl aliases:

~~~bash
for a in $(sed '/^alias /!d;s/^alias //;s/=.*$//' ~/.kubectl_aliases); do
  complete -F _complete_alias "$a"
done
~~~

The `_complete_alias` function is provided by complete-alias and it can be used to enable completion for every alias in general (as long as the aliased command has completion itself).

complete-alias depends on [bash-completion](https://github.com/scop/bash-completion), so you have to install it too.

If you use macOS, it won't work on the built-in version of Bash, because this is Bash version 3.2. You have to install Bash 4.1+ and bash-completion 2+.

**Comment by imduffy15** [comment]
Works perfectly. Thank you @weibeld 

@ahmetb Are you open to a PR that places this advice into the readme? :)

**Comment by ahmetb** [comment]
We can link from the readme, sure.
