### ISSUE TITLE
rename dep to d ?

### ISSUE THREAD

**Issue by toshi0383** [ahmetb/kubectl-aliases#24]
Hi, thanks for sharing super useful aliases!

I have a question.
Is there any concern about keeping long name `dep` ? To me it's a bit too long for an alias.
Doesn't `kgd` makes sense to you?

**Comment by ahmetb** [comment]
I'll say what I've been saying to many folks coming to this repo with suggestions: Consider forking and making changes. The generation script is easy to use. I personally prefer dep. I'm not trying to save two letters here and there and get even more cryptic.
