### ISSUE TITLE
Why not 'ed' for edit ?

### ISSUE THREAD

**Issue by QwertyJack** [ahmetb/kubectl-aliases#27]
commands: 'ed' -> edit

**Comment by ahmetb** [comment]
For the most part, we can’t keep adding stuff.  It slows shell startup down. Feel free to fork and update for yourself. 

Also editing resources manually is often not a good practice.

**Comment by Pivert** [comment]
Definitely, edit is the one that I miss the most in the labs.
I would change ex for x, and add e for edit.
