### ISSUE TITLE
Consider `kpf` for kubectl port-forward

### ISSUE THREAD

**Issue by incfly** [ahmetb/kubectl-aliases#33]
Port forward is used a lot in debugging Kubernetes workloads.

**Comment by ahmetb** [comment]
Assuming we'd only generate `kpf` and `kpfn`, this is fine to add.
Feel free to send a patch, I won't be able to get to doing it myself.

**Comment by incfly** [comment]
By `kpfn` what do you refer to? "n" is for what?

**Comment by ahmetb** [comment]
Did you read the readme? :)
