### ISSUE TITLE
Support more resources

### ISSUE THREAD

**Issue by piotrpersona** [ahmetb/kubectl-aliases#35]
It seems that there are only few k8s resources short names supported.
For example `daemonSet` is absent.
```
$ kgds
Unkown command kgds
```

```
$ kg ds
```

I've made list of k8s resources short names: https://gist.github.com/piotrpersona/abc28ed2c251c71127bd7d15300f2ae5

**Comment by ahmetb** [comment]
I encourage people to fork & add their own preferences.
