### ISSUE TITLE
function kubectl() {...} doesn't provide any autocomplete of the kubectl command

### ISSUE THREAD

**Issue by cguertin14** [ahmetb/kubectl-aliases#41]
Usually, using the `kubectl` command, there are autocompletes in a terminal (well, in my zsh terminal there is autocomplete).

I've noticed that when I added this line to my .zshrc:
```
function kubectl() { echo "+ kubectl $@">&2; command kubectl $@; }
```
I could not use any autocomplete feature of the kubectl command anymore in my terminal.

**Comment by ahmetb** [comment]
Feel free to just delete that from your file. This doesn't happen to me in my oh-my-zsh.

**Comment by cguertin14** [comment]
> Feel free to just delete that from your file. This doesn't happen to me in my oh-my-zsh.

I was more aiming for a fix rather than a "it doesn't work, so let's just forget about it" kinda thing. Lol.

**Comment by ahmetb** [comment]
The reason there are over 200 forks of this repo is because we cannot do everything on the core. Everyone wants something different. The project is rather static and small, you can fork & maintain. We don't add anything new.

I simply deleted that line in my local copy, despite I'm the owner.

**Comment by cguertin14** [comment]
Ok, I did not notice the forks. I really thought that maybe the problem was a misconfig on my end or something like that, so I was curious. Thanks!
