### ISSUE TITLE
Consider adding "kgpv" and "kgpvc"

### ISSUE THREAD

**Issue by bharat-p** [ahmetb/kubectl-aliases#49]
Would be nice to add`kgpv` and `kgpvc` for `kubectl get pv` and `kubectl get pvc`respectively.

and maybe associated aliases for `describe` commands for `pv` and `pvc`.

Happy to send in a patch to include these

**Comment by ahmetb** [comment]
Please fork/maintain. I don’t plan on having all resource types. It slows down shell startup linearly.
