### ISSUE TITLE
Add aliases for resource 'job'

### ISSUE THREAD

**Issue by AndreyMatveyev** [ahmetb/kubectl-aliases#51]
Our team works with k8s jobs a lot. It would be nice to have a set of aliases for the resource 'job' similar to 'pod'.
For example,
`alias kgjb='kubectl get jobs'`
or
`alias kgj='kubectl get jobs'`

If you don't mind, I can add them and open a PR.

**Comment by ahmetb** [comment]
We aren’t accepting resources to save up speed. Please fork/edit.
