### ISSUE TITLE
would be nice to include aliases for PV & PVCs 

### ISSUE THREAD

**Issue by dmitry-mightydevops** [ahmetb/kubectl-aliases#56]

**Comment by faraujo427** [comment]
The fork https://github.com/rispa/kubectl-aliases adds these two. But I think it'd be nice for the main one to have these as well

**Comment by ahmetb** [comment]
People usually open issues/PRs to add these.
My recommendation is to fork. I personally never use PV/PVCs so I don't want these to slow my shell loading time by an additional 10-20%.
