### ISSUE TITLE
proposal: add alias of kubectl extension

### ISSUE THREAD

**Issue by Xunzhuo** [ahmetb/kubectl-aliases#67]
Can we add some alias of kubectl extension like:
`kr` - `kubectl krew`
`kri` - `kubectl krew install`
`krup` - `kubectl krew update`
`krug` - `kubectl krew upgrade`
`krrm` - `kubectl krew uninstall`
`kns` - `kubectl ns`
`kcx` - `kubectl ctx`

**Comment by ahmetb** [comment]
Does not belong here as it is not as generic. You already wrote them so your can use.
