### ISSUE TITLE
Add NetworkPolicy resource support

### ISSUE THREAD

**Issue by Rafaesp** [ahmetb/kubectl-aliases#7]
Network Policy would be useful. Maybe np as abbreviation?
Thanks!

**Comment by ahmetb** [comment]
I think it's too rarely used to be be added. We don't have even RS RC resources. 

Adding new resources causes exponential growth so we may end up with 300-400 new aliases if we actually try to add this. And it's bad for performance. 

But feel free to fork the repo and add it yourself. It's fairly easy.
