### ISSUE TITLE
Support for --dry-run=client 

### ISSUE THREAD

**Issue by buckleyGI** [ahmetb/kubectl-aliases#71]
Just did my CKAD exam and one of the useful tips we employed in this context was to dry run the commands before executing them.
This is currently not supported by this project right.
Would it be a good idea for me to add support for it?

--dry-run=client 

This is a flag (not a value flag) so adding the the word "dry" would do it I think.

**Comment by ahmetb** [comment]
The "write commands" are relatively low % of the list.  Namely only "delete" commands can benefit from this, and I am not sure if one would actually benefit that much from dry-run=client deletion. :)

Please explain which one of the commands would benefit from this.

**Comment by buckleyGI** [comment]
The CKAD exam is also and exercise in creating objects quickly as you will not pass it if you type out all the yaml.

So we are drilled with using imperative commands to quickly constuct resource.

Some examples
`
k create deploy x --image x --dry-run=client -o yaml > x.yaml`

Now we are free to first edit the file for properties which aren't available at the command line e.g. adjust the container name, specify a service account etc

`k run x --image x --expose --port 80 --dry-run=client -o yaml > x.yaml`

Bam, now we have a pod and a service at the same time and ready to be edited/tweaked before applying

With some kubectl-aliases both scenario's would translate to 
```

kcdepdryoyaml x --image x > x.yaml

krdryoyaml x --image x --expose --port 80 > x.yaml
```

And now, when I'm writing this out, I see that the command 'create' and 'run' are not supported at the moment.
Were these intentionally left out?

Maybe you want to keep a more narrow focus with this project?

**Comment by buckleyGI** [comment]
I was under the impression that this project reflected over the cli command/options programmatically, generated the abbreviation, reported on duplicates that needed disambiguation, and then either blocklisted certain combinations or translated commands/options to aliases that removes the ambiguity as was done with the following instance
d=describe
d=>rm=delete

**Comment by ahmetb** [comment]
You're right but this project only has delete command's aliases where dry run can apply. And is it that much valuable there?

We don't offer programmatically generated aliases for create/apply really.

**Comment by buckleyGI** [comment]
Dry run for the delete command doesn't add value IMO.

If it is not the desire to have the create/run/expose commands in scope I suggest we close this issue. If you think this has a place I can start contributing.
