### ISSUE TITLE
Minor issue while running the python script

### ISSUE THREAD

**Issue by amitmavgupta** [ahmetb/kubectl-aliases#74]
Hi Ahmed,

When a user tries running the script (minus cloning the repo) it apparently seeks license_header. Would be good to add a small note that the user can just create a base license_header file as the script looks for that in the respective path.

Traceback (most recent call last):
  File "/Users/amit/generate_aliases.py", line 194, in <module>
    main()
  File "/Users/amit/generate_aliases.py", line 108, in main
    with open(header_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/amit/license_header'

bash-3.2$ touch license_header

helps mitigate this minor issue.

Thanks!
-Amit

**Comment by ahmetb** [comment]
sorry I don't understand the problem. there's a license_header file that comes with the repo. I'm not sure why it's necessary to run the script out of this working directory.
