### ISSUE TITLE
Support cronjobs and jobs

### ISSUE THREAD

**Issue by pjanuario** [ahmetb/kubectl-aliases#8]
Would be great to be able to do

`kgcron` and `kgj` or `kgjob`

**Comment by ahmetb** [comment]
There are many resource types that are not provided on purpose. Cron and Job are only two of them. I don't think they're as commonly used (however, feel free to fork it and add them, it's not that difficult).

Adding new types increases the number of aliases exponentially.

Also you can still use `kg cron` and `kg job` and `krmall job` etc.

**Comment by pjanuario** [comment]
Those commands are exactly what I have been using, I understand that it increases the amount of alias. 
Thanks for the awesome alias list anyway. 👍

**Comment by ahmetb** [comment]
No problem, just fork the project and add them here:

https://github.com/ahmetb/kubectl-aliases/blob/fbeff1c4483de17762722edc7c790c389390709e/generate_aliases.py#L46

**Comment by pjanuario** [comment]
No need, since will never be merged in the master I prefer not maintaining forks until I see something I can't live without.
Thanks.

**Comment by ahmetb** [comment]
The master isn't updated much anymore anyway. :) I think it has matured.

**Comment by deepaksood619** [comment]
`kj cj` works for me
