### ISSUE TITLE
Autocompletion does not work

### ISSUE THREAD

**Issue by khushijain21** [ahmetb/kubectl-aliases#80]
The kubectl auto completion does not work with aliases

On tab it shows the files in current directory instead of kubectl completion
```
$ kgpon 
.git/           .gitattributes  .gitignore      ATP/            Jenkins/        Jenkins_CI/     docs/           nukeConfig/     scripts/        
```

**Comment by ahmetb** [comment]
This is a problem with your shell. Use zsh.
